### ISSUE TITLE
Modify the apply to minecarts chests as well

### ISSUE THREAD

**Issue by rourke750** [gipsy-king/Burricos#1]
How difficult would this be to modify to minecart chests as well?  I'm thinking this could be a cool feature to have in the future and it would be nice to have it standby if needed.  Would a config size for how big it could be, be viable as well?

**Comment by benjajaja** [comment]
Shouldn't be too difficult, but it would need a round of retesting since a lot of stuff in the plugin either checks for- or assumes entities being horses and so on.

The size could be set, yes, but I'm pretty sure that anyway the largest inventory view is that of a double chest, and anything less than that wouldn't make sense, since a minecart chest has already 27 slots.
